name = "devops-portfolio"
compatibility_date = "2024-08-26"

[env.production]
name = "devops-portfolio"

[[env.production.routes]]
pattern = "*"
zone_name = "your-domain.com"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200